// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/api/internal/pause-over-limit": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/jobs/:jobId/status": {
    params: {
      "jobId": string;
    };
  };
  "/apps/discountflow/pack": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/api/jobs/run": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/campaigns/:id/edit/cart-value": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/:id/edit/tiered": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/:id/edit/range": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/:id/edit/bxgy": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/:id/edit/pack": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/new/cart-value": {
    params: {};
  };
  "/app/campaigns/new/percentage": {
    params: {};
  };
  "/app/campaigns/new/tiered": {
    params: {};
  };
  "/app/campaigns/new/range": {
    params: {};
  };
  "/app/campaigns/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/app/campaigns/new/bxgy": {
    params: {};
  };
  "/app/campaigns/new/pack": {
    params: {};
  };
  "/app/campaigns": {
    params: {};
  };
  "/app/plans/confirm": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/jobs-demo": {
    params: {};
  };
  "/app/support": {
    params: {};
  };
  "/app/plans": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/api/internal/pause-over-limit" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/api/jobs/:jobId/status" | "/apps/discountflow/pack" | "/webhooks/orders/create" | "/webhooks/shop/redact" | "/api/jobs/run" | "/auth/login" | "/auth/*" | "/app" | "/app/campaigns/:id/edit/cart-value" | "/app/campaigns/:id/edit/tiered" | "/app/campaigns/:id/edit/range" | "/app/campaigns/:id/edit/bxgy" | "/app/campaigns/:id/edit/pack" | "/app/campaigns/new/cart-value" | "/app/campaigns/new/percentage" | "/app/campaigns/new/tiered" | "/app/campaigns/new/range" | "/app/campaigns/:id/edit" | "/app/campaigns/new/bxgy" | "/app/campaigns/new/pack" | "/app/campaigns" | "/app/plans/confirm" | "/app/analytics" | "/app/jobs-demo" | "/app/support" | "/app/plans";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/api.internal.pause-over-limit.tsx": {
    id: "routes/api.internal.pause-over-limit";
    page: "/api/internal/pause-over-limit";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.jobs.$jobId.status.tsx": {
    id: "routes/api.jobs.$jobId.status";
    page: "/api/jobs/:jobId/status";
  };
  "routes/apps.discountflow.pack.tsx": {
    id: "routes/apps.discountflow.pack";
    page: "/apps/discountflow/pack";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/api.jobs.run.tsx": {
    id: "routes/api.jobs.run";
    page: "/api/jobs/run";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/campaigns/:id/edit/cart-value" | "/app/campaigns/:id/edit/tiered" | "/app/campaigns/:id/edit/range" | "/app/campaigns/:id/edit/bxgy" | "/app/campaigns/:id/edit/pack" | "/app/campaigns/new/cart-value" | "/app/campaigns/new/percentage" | "/app/campaigns/new/tiered" | "/app/campaigns/new/range" | "/app/campaigns/:id/edit" | "/app/campaigns/new/bxgy" | "/app/campaigns/new/pack" | "/app/campaigns" | "/app/plans/confirm" | "/app/analytics" | "/app/jobs-demo" | "/app/support" | "/app/plans";
  };
  "routes/app.campaigns.$id.edit_.cart-value.tsx": {
    id: "routes/app.campaigns.$id.edit_.cart-value";
    page: "/app/campaigns/:id/edit/cart-value";
  };
  "routes/app.campaigns.$id.edit_.tiered.tsx": {
    id: "routes/app.campaigns.$id.edit_.tiered";
    page: "/app/campaigns/:id/edit/tiered";
  };
  "routes/app.campaigns.$id.edit_.range.tsx": {
    id: "routes/app.campaigns.$id.edit_.range";
    page: "/app/campaigns/:id/edit/range";
  };
  "routes/app.campaigns.$id.edit_.bxgy.tsx": {
    id: "routes/app.campaigns.$id.edit_.bxgy";
    page: "/app/campaigns/:id/edit/bxgy";
  };
  "routes/app.campaigns.$id.edit_.pack.tsx": {
    id: "routes/app.campaigns.$id.edit_.pack";
    page: "/app/campaigns/:id/edit/pack";
  };
  "routes/app.campaigns.new.cart-value.tsx": {
    id: "routes/app.campaigns.new.cart-value";
    page: "/app/campaigns/new/cart-value";
  };
  "routes/app.campaigns.new.percentage.tsx": {
    id: "routes/app.campaigns.new.percentage";
    page: "/app/campaigns/new/percentage";
  };
  "routes/app.campaigns.new.tiered.tsx": {
    id: "routes/app.campaigns.new.tiered";
    page: "/app/campaigns/new/tiered";
  };
  "routes/app.campaigns.new.range.tsx": {
    id: "routes/app.campaigns.new.range";
    page: "/app/campaigns/new/range";
  };
  "routes/app.campaigns.$id.edit.tsx": {
    id: "routes/app.campaigns.$id.edit";
    page: "/app/campaigns/:id/edit";
  };
  "routes/app.campaigns.new.bxgy.tsx": {
    id: "routes/app.campaigns.new.bxgy";
    page: "/app/campaigns/new/bxgy";
  };
  "routes/app.campaigns.new.pack.tsx": {
    id: "routes/app.campaigns.new.pack";
    page: "/app/campaigns/new/pack";
  };
  "routes/app.campaigns._index.tsx": {
    id: "routes/app.campaigns._index";
    page: "/app/campaigns";
  };
  "routes/app.plans_.confirm.tsx": {
    id: "routes/app.plans_.confirm";
    page: "/app/plans/confirm";
  };
  "routes/app.analytics.tsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.jobs-demo.tsx": {
    id: "routes/app.jobs-demo";
    page: "/app/jobs-demo";
  };
  "routes/app.support.tsx": {
    id: "routes/app.support";
    page: "/app/support";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.plans.tsx": {
    id: "routes/app.plans";
    page: "/app/plans";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/api.internal.pause-over-limit": typeof import("./app/routes/api.internal.pause-over-limit.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/api.jobs.$jobId.status": typeof import("./app/routes/api.jobs.$jobId.status.tsx");
  "routes/apps.discountflow.pack": typeof import("./app/routes/apps.discountflow.pack.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/api.jobs.run": typeof import("./app/routes/api.jobs.run.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.campaigns.$id.edit_.cart-value": typeof import("./app/routes/app.campaigns.$id.edit_.cart-value.tsx");
  "routes/app.campaigns.$id.edit_.tiered": typeof import("./app/routes/app.campaigns.$id.edit_.tiered.tsx");
  "routes/app.campaigns.$id.edit_.range": typeof import("./app/routes/app.campaigns.$id.edit_.range.tsx");
  "routes/app.campaigns.$id.edit_.bxgy": typeof import("./app/routes/app.campaigns.$id.edit_.bxgy.tsx");
  "routes/app.campaigns.$id.edit_.pack": typeof import("./app/routes/app.campaigns.$id.edit_.pack.tsx");
  "routes/app.campaigns.new.cart-value": typeof import("./app/routes/app.campaigns.new.cart-value.tsx");
  "routes/app.campaigns.new.percentage": typeof import("./app/routes/app.campaigns.new.percentage.tsx");
  "routes/app.campaigns.new.tiered": typeof import("./app/routes/app.campaigns.new.tiered.tsx");
  "routes/app.campaigns.new.range": typeof import("./app/routes/app.campaigns.new.range.tsx");
  "routes/app.campaigns.$id.edit": typeof import("./app/routes/app.campaigns.$id.edit.tsx");
  "routes/app.campaigns.new.bxgy": typeof import("./app/routes/app.campaigns.new.bxgy.tsx");
  "routes/app.campaigns.new.pack": typeof import("./app/routes/app.campaigns.new.pack.tsx");
  "routes/app.campaigns._index": typeof import("./app/routes/app.campaigns._index.tsx");
  "routes/app.plans_.confirm": typeof import("./app/routes/app.plans_.confirm.tsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.tsx");
  "routes/app.jobs-demo": typeof import("./app/routes/app.jobs-demo.tsx");
  "routes/app.support": typeof import("./app/routes/app.support.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.plans": typeof import("./app/routes/app.plans.tsx");
};